name: daily-50-commits

# KST(UTC+9) 00:05 ⇔ UTC 15:05
on:
  schedule:
    - cron:  '5 15 * * *'
  workflow_dispatch:      # 수동 실행도 가능

jobs:
  spammy-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}   # 위에서 등록한 토큰

    - name: Set git identity
      run: |
        git config user.name  "github-action[bot]"
        git config user.email "41898282+github-action[bot]@users.noreply.github.com"

    - name: Make 50 commits
      env:
        TZ: Asia/Seoul
      run: |
        for i in $(seq 1 50); do
          printf '%s\n' "$(date '+%Y-%m-%d %H:%M:%S')" >> README.md
          git add README.md
          git commit -m "chore(auto): $(date '+%F %T') [$i/50]"
        done
        # 한꺼번에 50개 푸시 (푸시 1회 = API 호출 1회)
        git push
