name: daily-50-commits

# KST(UTC+9) 00:05 ⇔ UTC 15:05
on:
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch:      # 수동 실행도 가능

jobs:
  spammy-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.DEAN_PAT }}

    - name: Set git identity
      run: |
        git config user.name  "github-action[bot]"
        git config user.email "41898282+github-action[bot]@users.noreply.github.com"

    - name: Make 50 commits
      env:
        TZ: Asia/Seoul
      run: |
        printf '\n%s\n' "$(date '+%Y-%m-%d %H:%M:%S')" >> README.md
        git add README.md
        git commit -m "chore(auto): $(date '+%F %T') [$i/50]"
        git push
